import bycrypt from "bcryptjs";

/**
 * Hashes the given password using a salt generated by bcrypt, and returns the resulting hash.
 * @param password The password to hash.
 * @returns A promise that resolves to the hashed password.
 */
export const hashPassword = async (password: string): Promise<string> => {
    const salt = await bycrypt.genSalt(10);
    return bycrypt.hash(password, salt);
};

/**
 * Compares a given password with a hashed password to check if they match.
 * @param password The password to compare.
 * @param hashedPassword The hashed password to compare against.
 * @returns A promise that resolves to true if the passwords match, false otherwise.
 */
export const comparePassword = async (
    password: string,
    hashedPassword: string
) => {
    return bycrypt.compare(password, hashedPassword);
};
